In [1]:
import matplotlib.pyplot as plt
import numpy as np
from typing import Union, Tuple, List
from utils import ImageBatchGenerator, ManualConvLayer,Flatten,SigmoidAct,TanhAct

In [3]:
dogs_path = r"C:\Users\ayhan\Desktop\ml-collection\data\ten_animals\raw-img\dog"
cats_path = r"C:\Users\ayhan\Desktop\ml-collection\data\ten_animals\raw-img\cat"
img_batch = ImageBatchGenerator({"dog":dogs_path, "cat":cats_path},batch_size=8,network_input_size=(50,50))
conv_layer = ManualConvLayer(kernel_shape=(3,3),kernel_count=5,padding=2)
output = conv_layer.forward(img_batch.batch_matrix)
output.shape 

(52, 52, 5, 8)

#### now lets test out our sigmoidAct and TanhAct


In [2]:
X = np.array([2, 3, 4])
# S(X)	0.8807970779779563
# S'(X)	0.1049935854034503 sigmoid prime(X)
sigmoid_act = SigmoidAct()
result = sigmoid_act.forward(np.array([2, 3, 4]))
result

array([0.88079708, 0.95257413, 0.98201379])

In [3]:
sigmoid_act.backward(1)

array([0.10499359, 0.04517666, 0.01766271])

In [4]:
print(sigmoid_act.backward(0.2))
print(result*(1-result)*0.2)

[0.02099872 0.00903533 0.00353254]
[0.02099872 0.00903533 0.00353254]


In [5]:
tanh_act = TanhAct()
res = tanh_act.forward(X)
res # expected :[0.964027580076,0.995054753687,0.999329299739]


array([0.96402758, 0.99505475, 0.9993293 ])

In [7]:
print(tanh_act.backward(0.2))
print((1-res**2)*0.2)

[0.01413016 0.00197321 0.00026819]
[0.01413016 0.00197321 0.00026819]


---
---

### now we will implement backprop. of pooling layer
- again no derivatives needed, we just need to multiply the outer deriv with the mask


<img src="..\..\data\markdown_images\pooling_backprop.png" width="600" height="400" alt="Image description">
